name: Deploy to VPS

on:
  push:
    branches: [ main ]   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Copy project files to VPS
      run: |
        rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@mailbox.sharda.co.in:/home/mailbox/

    - name: Install dependencies and build on VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/mailbox &&
          npm install &&
          npm run build &&
          pm2 restart all || pm2 start npm --name mailbox -- start
        "
