# name: Deploy to VPS

# on:
#   push:
#     branches: [ main ]   # or your default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up SSH key
#       uses: webfactory/ssh-agent@v0.8.0
#       with:
#         ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

#     - name: Copy project files to VPS
#       run: |
#         rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@168.231.120.171:/home/mailbox/

#     - name: Install dependencies
#       run: ssh -o StrictHostKeyChecking=no root@168.231.120.171 "cd /home/mailbox && npm install"

#     - name: Build project
#       run: ssh -o StrictHostKeyChecking=no root@168.231.120.171 "cd /home/mailbox && npm run build"

#     - name: Restart PM2
#       run: ssh -o StrictHostKeyChecking=no root@168.231.120.171 "cd /home/mailbox && pm2 restart all || pm2 start npm --name mailbox -- start"




name: Deploy Mailbox to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.VPS_PORT }}   # Uncomment if not using port 22
          timeout: 1200           # 20 minutes for connection
          command_timeout: 1200   # 20 minutes for commands
          script: |
            set -e  # Exit on error
            cd /home/mailbox
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            # Optional: ensure branch is correct
            # git checkout main
            rm -rf .next node_modules
            npm install --omit=dev
            npm run build
            pm2 list
            pm2 restart mailbox || pm2 start npm --name "mailbox" -- start
            pm2 save
